app:
  debug: false
  host: "0.0.0.0"
  port: 5000

prometheus:
  metrics_path: "/metrics" ## Endpoint for metrics
  default_labels:
    app_name: "teladoc_task_exporter"
    environment: "development"

tasks:
  allowed_statuses: ["completed", "failed", "succeeded"]
