apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-exporter
  template:
    metadata:
      labels:
        app: task-exporter
    spec:
      containers:
      - name: task-exporter
        image: your-registry/task-exporter:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: task-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: task-exporter
spec:
  selector:
    app: task-exporter
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
