version: '3'

services:
  task-exporter:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DEBUG=False
    volumes:
      - ./config.yaml:/app/config.yaml

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - task-exporter
